# Generated by Django 3.0.7 on 2020-08-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUsers',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
