# Generated by Django 3.0.7 on 2020-08-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusers',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
