# Generated by Django 3.0.7 on 2020-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgo', '0002_auto_20200820_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiusers',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
